[project]
name = "gpostmaster-domains-data"
dynamic = ["version"]
description = "Downloads and flattends data from Google Postmaster Tools (GPT)"
readme = "README.md"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
authors = [
    { name = "Valentin Henon", email = "vhenon@mindbaz.com" }
]
urls = { repository = "https://github.com/Mindbaz/python-gpostmaster-domains-data" }
requires-python = ">=3.9"
dependencies = [
    "pydantic",
    "google-api-python-client>=2.196.0",
    "google-auth-httplib2",
    "google-auth-oauthlib",
]

[project.scripts]
gpt_create_domain = "entry_points_googlepostmasterapi.gpt_create_domain:run"
gpt_delete_domain = "entry_points_googlepostmasterapi.gpt_delete_domain:run"
gpt_dl_all_data = "entry_points_googlepostmasterapi.gpt_dl_all_data:run"
gpt_dl_domain_data = "entry_points_googlepostmasterapi.gpt_dl_domain_data:run"
gpt_dl_domains = "entry_points_googlepostmasterapi.gpt_dl_domains:run"
gpt_get_domain_verify_token = "entry_points_googlepostmasterapi.gpt_get_domain_verify_token:run"
gpt_verify_domain = "entry_points_googlepostmasterapi.gpt_verify_domain:run"

[project.optional-dependencies]
dev = [
    "pynose",
    "coverage",
]

[tool.setuptools.dynamic]
version = { attr = "googlepostmasterapi.__version__" }

[tool.setuptools.packages.find]
where = ["."]
include = [
    "googlepostmasterapi",
    "entry_points_googlepostmasterapi",
]
